In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
iris=pd.read_csv('IRIS.csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [36]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df1=iris.loc[iris['Species'] =='Iris-setosa']
df1

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [9]:
t_count=np.count_nonzero(df1.SepalLengthCm)
t_count

50

In [12]:
temp=df1.SepalLengthCm.unique()
temp

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3])

In [14]:
freq=[]
prob=[]
count=0

for i in temp:
    for j in df1['SepalLengthCm']:
        if i==j:
            count=count+1
    freq.append(count)
    prob.append(count/t_count)
    count=0


print(prob)
print(temp)
print(freq)

[0.16, 0.08, 0.04, 0.08, 0.16, 0.1, 0.06, 0.1, 0.02, 0.02, 0.04, 0.06, 0.04, 0.02, 0.02]
[5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3]
[8, 4, 2, 4, 8, 5, 3, 5, 1, 1, 2, 3, 2, 1, 1]


In [15]:
df3=pd.DataFrame(
    {'sepal length': temp,
     'frequency':freq,
     'probability':prob})
df3

sepal length  frequency  probability
0            5.1          8         0.16
1            4.9          4         0.08
2            4.7          2         0.04
3            4.6          4         0.08
4            5.0          8         0.16
5            5.4          5         0.10
6            4.4          3         0.06
7            4.8          5         0.10
8            4.3          1         0.02
9            5.8          1         0.02
10           5.7          2         0.04
11           5.2          3         0.06
12           5.5          2         0.04
13           4.5          1         0.02
14           5.3          1         0.02

In [16]:
expect_value=0
i=0
for value in temp:
    expect_value= expect_value + (value * prob[i])
    i=i+1

print('expected value=',expect_value)

expected value= 5.005999999999999


In [18]:
df2=iris.loc[iris['Species'] =='Iris-virginica']
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   
105  106            7.6           3.0            6.6           2.1   
106  107            4.9           2.5            4.5           1.7   
107  108            7.3           2.9            6.3           1.8   
108  109            6.7           2.5            5.8           1.8   
109  110            7.2           3.6            6.1           2.5   
110  111            6.5           3.2            5.1           2.0   
111  112            6.4           2.7            5.3           1.9   
112  113            6.8           3.0            5.5           2.1   
113  114            5.7           2.5            5.0           2.0   
114  115            5.8           2.8            5.1           2.4   
115  116            6.4           3.2            5.3           2.3   
116  117            6.5           3.0            5.5           1.8   
117  118            7.7           3.8            6.7           2.2   
118  119            7.7           2.6            6.9           2.3   
119  120            6.0           2.2            5.0           1.5   
120  121            6.9           3.2            5.7           2.3   
121  122            5.6           2.8            4.9           2.0   
122  123            7.7           2.8            6.7           2.0   
123  124            6.3           2.7            4.9           1.8   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
126  127            6.2           2.8            4.8           1.8   
127  128            6.1           3.0            4.9           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
100  Iris-virginica  
101  Iris-virginica  
102  Iris-virginica  
103  Iris-virginica  
104  Iris-virginica  
105  Iris-virginica  
106  Iris-virginica  
107  Iris-virginica  
108  Iris-virginica  
109  Iris-virginica  
110  Iris-virginica  
111  Iris-virginica  
112  Iris-virginica  
113  Iris-virginica  
114  Iris-virginica  
115  Iris-virginica  
116  Iris-virginica  
117  Iris-virginica  
118  Iris-virgini

In [21]:
t_count1=np.count_nonzero(df1.PetalLengthCm)
t_count1

50

In [23]:
temp1=df1.PetalLengthCm.unique()
temp1

array([1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9])

In [30]:
freq=[]
prob=[]
count=0

for i in temp1:
    for j in df2['SepalLengthCm']:
        if i==j:
            count=count+1
    freq.append(count)
    prob.append(count/t_count1)
    count=0


print(prob)
print(temp1)
print(freq)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9]
[0, 0, 0, 0, 0, 0, 0, 0, 0]


In [33]:
df4=pd.DataFrame(
    {'petal length': temp1,
     'freq':freq,
     'probability':prob})
df4

petal length  freq  probability
0           1.4     0          0.0
1           1.3     0          0.0
2           1.5     0          0.0
3           1.7     0          0.0
4           1.6     0          0.0
5           1.1     0          0.0
6           1.2     0          0.0
7           1.0     0          0.0
8           1.9     0          0.0

In [27]:
expect_value=0
i=0
for value in temp1:
    expect_value= expect_value + (value * prob[i])
    i=i+1

print('expected value=',expect_value)

expected value= 0.0
