In [1]:
import numpy as np
import pandas as pd

In [2]:
a = [0,0,1,0,1] #Sum = 2
b = [1,0,0,1,1] #Sum = 3
a1 = np.array(a)
a2 = np.array(b)
d1_1 = [a1,a2]
d1_2 = pd.DataFrame(d1_1,index = ['Array-1','Array-2'])
d1_2


0  1  2  3  4
Array-1  0  0  1  0  1
Array-2  1  0  0  1  1

In [3]:
s1 = np.sum(a1)
s2 = np.sum(a2)
d2_1 = [[s1,s2],[s1*3,s2*3]]
d2_2 = pd.DataFrame(d2_1,columns = ['Array-1','Array-2'],index = ['Sum', 'Mul'])
d2_2

Array-1  Array-2
Sum        2        3
Mul        6        9

In [4]:
a3 = np.array(b)
bool_val = (a1 == a2) #If Element Of Array-1 Equals To Array-2
d3_1 = [a1,a2,np.logical_and(a1,a3),np.logical_or(a1,a3),np.logical_not(a1,a3),bool_val]
d3_2 = pd.DataFrame(d3_1,index = ['Array-1','Array-2','Logical AND','Logical OR','Logical NOT','Boolean Operation'])
d3_2

0      1      2      3     4
Array-1                0      0      1      0     1
Array-2                1      0      0      1     1
Logical AND        False  False  False  False  True
Logical OR          True  False   True   True  True
Logical NOT            1      1      0      1     0
Boolean Operation  False   True  False  False  True

In [5]:
td1 = [[1,0,1],[0,1,0],[0,1,1]]
td2 = [[1,1,1],[1,1,0],[0,0,1]]
t = np.array(td1)
d = np.array(td2)
td = np.array(td2)
bool_val0 = (t[0] == d[0])
bool_val1 = (t[1] == d[1])
bool_val2 = (t[2] == d[2])
d3_1 = [[t[0],d[0],np.logical_and(t[0],td[0]),np.logical_or(t[0],td[0]),np.logical_not(t[0],td[0]),bool_val0],[t[1],d[2],np.logical_and(t[1],td[1]),np.logical_or(t[1],td[1]),np.logical_not(t[1],td[1])],[t[2],d[2],np.logical_and(t[2],td[2]),np.logical_or(t[2],td[2]),np.logical_not(t[2],td[2])]]
d3_2 = pd.DataFrame(d3_1,columns = ['Array-1','Array-2','Logical AND','Logical OR','Logical NOT','Boolean Operation'])
d3_2

Array-1    Array-2           Logical AND           Logical OR  \
0  [1, 0, 1]  [1, 1, 1]   [True, False, True]   [True, True, True]   
1  [0, 1, 0]  [0, 0, 1]  [False, True, False]  [True, True, False]   
2  [0, 1, 1]  [0, 0, 1]  [False, False, True]  [False, True, True]   

  Logical NOT    Boolean Operation  
0   [0, 1, 0]  [True, False, True]  
1   [1, 0, 1]                 None  
2   [1, 0, 0]                 None

In [6]:
d4_1 = [[t[0],d[0],'[0:2]',t[0,0:2],d[0,0:2]],[t[1],d[1],'[0:1]',t[1,0:1],d[1,0:1]]]
d4_2 = pd.DataFrame(d4_1,columns = ['Array-1','Array-2','Slice Range','Sliced Array-1','Sliced Array-2'])
d4_2

Array-1    Array-2 Slice Range Sliced Array-1 Sliced Array-2
0  [1, 0, 1]  [1, 1, 1]       [0:2]         [1, 0]         [1, 1]
1  [0, 1, 0]  [1, 1, 0]       [0:1]            [0]            [1]

In [7]:
arr = np.arange(1,11,1)
res_arr = np.reshape(arr,(2,5))
resi_arr = np.resize(arr,(4,4))
hsp_arr = np.hsplit(resi_arr,2)
print(f'Original Array:{arr}\n\nreshaped Array:\n{res_arr}\n\nResized Array:\n{resi_arr}\n\nSplitte Array\n{hsp_arr}')

Original Array:[ 1  2  3  4  5  6  7  8  9 10]

reshaped Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Resized Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1  2]
 [ 3  4  5  6]]

Splitte Array
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [ 3,  4]]), array([[3, 4],
       [7, 8],
       [1, 2],
       [5, 6]])]


In [8]:
ext_arr = np.array([0, 1, 2, 1, 3, 2, 1, 2, 2, 0, 1, 4])
cond1 = (ext_arr == 1)
cond2 = (ext_arr == 2)
np.extract(cond1,ext_arr), np.extract(cond2,ext_arr)

(array([1, 1, 1, 1]), array([2, 2, 2, 2]))

In [9]:
mft = pd.MultiIndex.from_tuples([(190031930, 'varun myneni'), (190031930, 'Section-3'),
                                 (190031840, 'abhinav pamarthi'), (190031840, 'Section-12')],
                                names =['Id Num', 'Name & Sec'])
dfmi= mft.to_frame()
dfmi

Id Num        Name & Sec
Id Num    Name & Sec                                   
190031930 varun myneni      190031930      varun myneni
          Section-3         190031930         Section-3
190031840 abhinav pamarthi  190031840  abhinav pamarthi
          Section-12        190031840        Section-12

In [10]:
df = pd.read_csv('xAPI-Edu-Data.csv')
df.head(10)

gender NationalITy PlaceofBirth       StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
5      F          KW       KuwaIT    lowerlevel    G-04         A    IT   
6      M          KW       KuwaIT  MiddleSchool    G-07         A  Math   
7      M          KW       KuwaIT  MiddleSchool    G-07         A  Math   
8      F          KW       KuwaIT  MiddleSchool    G-07         A  Math   
9      F          KW       KuwaIT  MiddleSchool    G-07         B    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   
5        F   Father           42                30                 13   
6        F   Father           35                12                  0   
7        F   Father           50                10                 15   
8        F   Father           12                21                 16   
9        F   Father           70                80                 25   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   
5          70                   Yes                      Bad   
6          17                    No                      Bad   
7          22                   Yes                     Good   
8          50                   Yes                     Good   
9          70                   Yes                     Good   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M  
5            Above-7     M  
6            Above-7     L  
7            Under-7     M  
8            Under-7     M  
9            Under-7     M

In [11]:
df.describe()

raisedhands  VisITedResources  AnnouncementsView  Discussion
count   480.000000        480.000000         480.000000  480.000000
mean     46.775000         54.797917          37.918750   43.283333
std      30.779223         33.080007          26.611244   27.637735
min       0.000000          0.000000           0.000000    1.000000
25%      15.750000         20.000000          14.000000   20.000000
50%      50.000000         65.000000          33.000000   39.000000
75%      75.000000         84.000000          58.000000   70.000000
max     100.000000         99.000000          98.000000   99.000000

In [12]:
df.mean()

raisedhands          46.775000
VisITedResources     54.797917
AnnouncementsView    37.918750
Discussion           43.283333
dtype: float64

In [13]:
df.median()

raisedhands          50.0
VisITedResources     65.0
AnnouncementsView    33.0
Discussion           39.0
dtype: float64

In [14]:
df[10:5:-1]

gender NationalITy PlaceofBirth       StageID GradeID SectionID Topic  \
10      M          KW       KuwaIT  MiddleSchool    G-07         A  Math   
9       F          KW       KuwaIT  MiddleSchool    G-07         B    IT   
8       F          KW       KuwaIT  MiddleSchool    G-07         A  Math   
7       M          KW       KuwaIT  MiddleSchool    G-07         A  Math   
6       M          KW       KuwaIT  MiddleSchool    G-07         A  Math   

   Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
10        F   Father           50                88                 30   
9         F   Father           70                80                 25   
8         F   Father           12                21                 16   
7         F   Father           50                10                 15   
6         F   Father           35                12                  0   

    Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
10          80                   Yes                     Good   
9           70                   Yes                     Good   
8           50                   Yes                     Good   
7           22                   Yes                     Good   
6           17                    No                      Bad   

   StudentAbsenceDays Class  
10            Under-7     H  
9             Under-7     M  
8             Under-7     M  
7             Under-7     M  
6             Above-7     L

In [15]:
df_new = df[1:10]
df_new[df_new.columns[0:10]]

gender NationalITy PlaceofBirth       StageID GradeID SectionID Topic  \
1      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT    lowerlevel    G-04         A    IT   
5      F          KW       KuwaIT    lowerlevel    G-04         A    IT   
6      M          KW       KuwaIT  MiddleSchool    G-07         A  Math   
7      M          KW       KuwaIT  MiddleSchool    G-07         A  Math   
8      F          KW       KuwaIT  MiddleSchool    G-07         A  Math   
9      F          KW       KuwaIT  MiddleSchool    G-07         B    IT   

  Semester Relation  raisedhands  
1        F   Father           20  
2        F   Father           10  
3        F   Father           30  
4        F   Father           40  
5        F   Father           42  
6        F   Father           35  
7        F   Father           50  
8        F   Father           12  
9        F   Father           70